version: '3.7'

services:
  php:
    build:
      context: ../
      dockerfile: .docker/services/php/php.Dockerfile
    depends_on:
      - pgsql
      - mariadb
  nginx:
    build:
      context: ../
      dockerfile: .docker/services/nginx/nginx.Dockerfile
    depends_on:
      - php
  pgsql:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  mariadb:
    image: mariadb:11.1.2
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
